name: jaspr_material
description: This is the material library for the Jaspr web framework based on dart. This package adds some material components to the existing Jaspr ecosystem.
version: 0.2.2
repository: https://github.com/NonymousMorlock/jaspr_material
homepage: https://github.com/NonymousMorlock/jaspr_material

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  jaspr_lints: any
  lints: any
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ">=6.0.0 <11.0.0"
dependencies:
  jaspr: ">=0.22.0 <0.23.0"
